-- MySQL Script generated by MySQL Workbench
-- jue 16 nov 2023 16:20:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vapor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vapor` ;

-- -----------------------------------------------------
-- Schema vapor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vapor` ;
USE `vapor` ;

-- -----------------------------------------------------
-- Table `vapor`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vapor`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(100) NOT NULL,
  `nickname` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vapor`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vapor`.`categorias` (
  `id_categorias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categorias`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vapor`.`juegos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vapor`.`juegos` (
  `id_juegos` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `tamano` INT NULL,
  `id_categorias` INT NOT NULL,
  `imagen` VARCHAR(1000) NULL,
  PRIMARY KEY (`id_juegos`),
  UNIQUE INDEX `id_juegos_UNIQUE` (`id_juegos` ASC) VISIBLE,
  INDEX `fk_juegos_categorias1_idx` (`id_categorias` ASC) VISIBLE,
  CONSTRAINT `fk_juegos_categorias1`
    FOREIGN KEY (`id_categorias`)
    REFERENCES `vapor`.`categorias` (`id_categorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vapor`.`install`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vapor`.`install` (
  `id_install` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `id_usuarios` INT NOT NULL,
  `id_juegos` INT NOT NULL,
  PRIMARY KEY (`id_install`),
  INDEX `fk_install_usuarios_idx` (`id_usuarios` ASC) VISIBLE,
  INDEX `fk_install_juegos1_idx` (`id_juegos` ASC) VISIBLE,
  CONSTRAINT `fk_install_usuarios`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `vapor`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_install_juegos1`
    FOREIGN KEY (`id_juegos`)
    REFERENCES `vapor`.`juegos` (`id_juegos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
